File projectReports = new File(basedir, 'target/site/project-reports.html')
assert projectReports.exists()
assert projectReports.text.contains('href="it1-report.html">IT1 Report</a>')
assert projectReports.text.contains('IT1 Description')
File it1Report = new File(basedir, 'target/site/it1-report.html')
assert it1Report.exists()
assert it1Report.text.contains('IT1 Report')
assert it1Report.text.contains('View the Report')
File copiedIndex = new File(basedir, 'target/site/it1-report/index.html')
assert copiedIndex.exists()
